export const TECH_DOMAINS = [
  ".com",
  "admin panels",
  "AI",
  "analytics platforms",
  "APIs",
  "apps",
  "architecture diagrams",
  "auth services",
  "automation scripts",
  "B2B",
  "B2C",
  "backend services",
  "bold innovations",
  "breakthrough ideas",
  "cache layers",
  "category creators",
  "CI/CD",
  "cloud native",
  "cloud services",
  "collaboration tools",
  "communication platforms",
  "competitive edges",
  "components",
  "containers",
  "content delivery",
  "customer experiences",
  "cutting-edge solutions",
  "dashboards",
  "data lakes",
  "data pipelines",
  "data warehouses",
  "databases",
  "decentralized apps",
  "deployment systems",
  "developer tools",
  "DevOps tools",
  "digital products",
  "disruptors",
  "distributed systems",
  "docker images",
  "e-commerce platforms",
  "edge computing",
  "ETL systems",
  "event-driven systems",
  "experiences",
  "fault-tolerant systems",
  "frameworks",
  "frontend experiences",
  "full-stack apps",
  "game changers",
  "games",
  "GraphQL APIs",
  "gRPC services",
  "hackathon projects",
  "high-performance apps",
  "incredible experiences",
  "infrastructure",
  "innovation",
  "interfaces",
  "legacies",
  "libraries",
  "logging platforms",
  "low-latency systems",
  "market leaders",
  "microservices",
  "mobile-friendly",
  "modules",
  "monitoring systems",
  "moonshots",
  "MVPs",
  "networks",
  "next-gen platforms",
  "notification systems",
  "observability tools",
  "open source",
  "orchestration tools",
  "pipelines",
  "platforms",
  "productivity apps",
  "products",
  "proof of concepts",
  "prototypes",
  "queue systems",
  "reactive systems",
  "real-time apps",
  "recommendation systems",
  "resilient systems",
  "REST APIs",
  "SaaS",
  "scalable systems",
  "search engines",
  "seamless solutions",
  "secure systems",
  "serverless",
  "services",
  "side projects",
  "smart contracts",
  "solutions",
  "streaming platforms",
  "systems",
  "the future",
  "the next big thing",
  "tools",
  "transformative solutions",
  "transformative tech",
  "unicorn ideas",
  "user portals",
  "visions",
  "web apps",
  "web3",
  "websockets",
  "widgets",
  "world-class products",
  "world-class software"
];
